### ISSUE TITLE
presentation attack detection

### ISSUE THREAD

**Issue by DecentMakeover** [kgram007/Eulerian-Motion-Magnification#4]
Hi 

Thanks for sharing your work, 
I have a question. 

Can Eulerian-Motion-Magnification be used for Presentation attack detection? What do you think ?

Thanks in advance.

**Comment by kgram007** [comment]
Hi,

I am not the author of the paper on which this code is based on. I just made an implementation of the original work done by the team at MIT CSAIL. For further details view this page: http://people.csail.mit.edu/mrub/vidmag/
